### ISSUE TITLE
[question] how to retain extension status (activated/inactive) after browser start

### ISSUE THREAD

**Issue by ghost** [maxnikulin/alt-tong#2]
FF 57.03 x64 with AT 0.3 on W10 x64 b16299.r3

Every time the browser is restarted the extention status is _disabled_ and thus requires to be manually enabled again

**Comment by maxnikulin** [comment]
Are your talking about enabled/disabled extension status on the `about:addons` page? If so, please, look if there are some warnings or errors in "Web Developer"/"Browser console" [Ctrl+Shift+J]. Sorry, but I have no Windows 10 to test and I do not see any problem on linux.

On the other hand the state if alternative language setting is active is not preserved over closing the browser and starting it again. I did it intentionally. I consider alternative language as a temporary override, otherwise it should be changed in browser settings (`about:preferences`). I believed that browser restart is not a frequent event especially since installation of webextensions does not require browser restart (unlike XUL/XPCOM extensions earlier). So I do not see a scenario when lost state is really annoying and consider current behavior as a way to avoid a surprise with non-default preferences next day.

**Comment by ghost** [comment]
Thanks for the response.

Is not about enabling/disabling in `about:addons` but the extension being activated/inactive upon browser restart.

Commonly I would have `intl.accept_languages`, for a variety of reasons, set to blank `""` or wildcard `*`, however either is causing some bug with some other extension. With AT I got at least one of the two options (`*`) for the return headers.

In my daily workflow I face frequent browser restarts and thus been looking for some option to set the AT alternative as default and persistent across browser restarts. Suppose I will get used to manually reactive AT upon browser restart.
